# Generated by Django 3.2.4 on 2021-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='details',
        ),
        migrations.AddField(
            model_name='experience',
            name='board',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='percentage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
