# Generated by Django 3.2.4 on 2021-06-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20210616_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('c_link', models.CharField(max_length=255)),
            ],
        ),
    ]
