# Generated by Django 3.2.4 on 2021-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(default='', upload_to='certificate'),
            preserve_default=False,
        ),
    ]
