# Generated by Django 3.2.4 on 2021-06-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_achievement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='c_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
