# Generated by Django 3.2.4 on 2021-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_alter_achievement_c_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
