# Generated by Django 3.2.4 on 2021-06-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_achievement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='details',
            field=models.TextField(max_length=255),
        ),
    ]
