# Generated by Django 3.2.4 on 2021-06-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_alter_achievement_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='pdf')),
            ],
        ),
    ]
