# Generated by Django 3.2.4 on 2021-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('insta', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'AboutMe', 'verbose_name_plural': 'AboutMe'},
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
