# Generated by Django 3.2.4 on 2021-06-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(default='', upload_to='profile'),
        ),
    ]
