# Generated by Django 3.2.4 on 2021-06-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_alter_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(default='images/avatar-1.svg', upload_to='profile'),
        ),
    ]
